# Generated by Django 5.1.7 on 2025-03-18 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="scheduleddelivery",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="scheduleddelivery",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="scheduleddelivery",
            name="user_basket",
        ),
        migrations.RemoveField(
            model_name="scheduleddeliverydate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="scheduleddeliverydate",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="scheduleddelivery",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleddelivery",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="OneTimeDeliveryDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_date", models.DateField()),
                (
                    "scheduled_delivery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_delivery",
                        to="orders.scheduleddelivery",
                    ),
                ),
            ],
        ),
    ]
