# Generated by Django 5.1.7 on 2025-03-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_shipping_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimedeliverydate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="onetimedeliverydate",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleddelivery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleddelivery",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleddeliverydate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleddeliverydate",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
