# Generated by Django 5.1.7 on 2025-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_onetimedeliverydate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("delivered", "Delivered"),
                    ("in_progress", "In progress"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("in_transit", "In transit"),
                    ("confirmed", "Confirmed"),
                ],
                default="payment_pending",
                max_length=20,
            ),
        ),
    ]
