# Generated by Django 5.1.7 on 2025-03-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_session_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
