# Generated by Django 5.1.1 on 2025-01-29 11:01

import django.db.models.deletion
import product.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "name",
                    product.fields.CaseInsensitiveCharField(
                        max_length=255, unique=True
                    ),
                ),
                ("contact_no", models.CharField(max_length=15)),
                ("contact_no_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("term_condition", models.BooleanField(default=False)),
                ("sms_reminders", models.BooleanField(default=True)),
                ("email_reminders", models.BooleanField(default=True)),
                ("newletter_reminders", models.BooleanField(default=True)),
                (
                    "customer_type",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Company"), ("I", "Individual")],
                        default="I",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Stockholms län", "Stockholms län"),
                            ("Västernorrlands län", "Västernorrlands län"),
                            ("Västmanlands län", "Västmanlands län"),
                            ("Västra Götalands län", "Västra Götalands län"),
                            ("Östergötlands län", "Östergötlands län"),
                            ("Dalarnas län", "Dalarnas län"),
                            ("Gävleborgs län", "Gävleborgs län"),
                            ("Gotlands län", "Gotlands län"),
                            ("Hallands län", "Hallands län"),
                            ("Jämtlands län", "Jämtlands län"),
                            ("Jönköpings län", "Jönköpings län"),
                            ("Kalmar län", "Kalmar län"),
                            ("Kronobergs län", "Kronobergs län"),
                            ("Norrbottens län", "Norrbottens län"),
                            ("Örebro län", "Örebro län"),
                            ("Skåne län", "Skåne län"),
                            ("Södermanlands län", "Södermanlands län"),
                            ("Uppsala län", "Uppsala län"),
                            ("Värmlands län", "Värmlands län"),
                            ("Västerbottens län", "Västerbottens län"),
                            ("Blekinge län", "Blekinge län"),
                            ("Nordmalings län", "Nordmalings län"),
                        ],
                        max_length=80,
                        verbose_name="State",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("SE", "SWEDEN")],
                        default="SE",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[("BL", "Billing"), ("SP", "Shipping")],
                        default="BL",
                        max_length=2,
                        verbose_name="Delivery",
                    ),
                ),
                ("zipcode", models.IntegerField()),
                ("primary", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bakery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("phone_otp", models.CharField(blank=True, max_length=6, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_sms_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customer.customer",
                    ),
                ),
            ],
        ),
    ]
