# Generated by Django 5.1.1 on 2025-02-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customeraddress",
            old_name="bakery",
            new_name="customer",
        ),
    ]
