# Generated by Django 5.1.7 on 2025-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_rename_bakery_customeraddress_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="organization_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="vat_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
