# Generated by Django 5.1.1 on 2025-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_customer_id_customer_organization_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company_domain",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="organization_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
