# Generated by Django 5.1.1 on 2025-04-11 11:59

import product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=product.fields.CaseInsensitiveCharField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
