# Generated by Django 5.1.1 on 2025-04-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                blank=True,
                choices=[("C", "Company"), ("I", "Individual")],
                default="C",
                max_length=2,
                null=True,
                verbose_name="Customer Type",
            ),
        ),
    ]
