# Generated by Django 5.1.1 on 2025-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_customer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="state",
            field=models.CharField(max_length=80, verbose_name="State"),
        ),
    ]
