# Generated by Django 5.1.1 on 2025-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_customeraddress_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="state",
            field=models.CharField(
                choices=[
                    ("Stockholms", "Stockholms"),
                    ("Västernorrlands", "Västernorrlands"),
                    ("Västmanlands", "Västmanlands"),
                    ("Västra Götalands", "Västra Götalands"),
                    ("Östergötlands", "Östergötlands"),
                    ("Dalarnas", "Dalarnas"),
                    ("Gävleborgs", "Gävleborgs"),
                    ("Gotlands", "Gotlands"),
                    ("Hallands", "Hallands"),
                    ("Jämtlands", "Jämtlands"),
                    ("Jönköpings", "Jönköpings"),
                    ("Kalmar", "Kalmar"),
                    ("Kronobergs", "Kronobergs"),
                    ("Norrbottens", "Norrbottens"),
                    ("Örebro", "Örebro"),
                    ("Skåne", "Skåne"),
                    ("Södermanlands", "Södermanlands"),
                    ("Uppsala", "Uppsala"),
                    ("Värmlands", "Värmlands"),
                    ("Västerbottens", "Västerbottens"),
                    ("Blekinge", "Blekinge"),
                    ("Nordmalings", "Nordmalings"),
                ],
                max_length=80,
                verbose_name="State",
            ),
        ),
    ]
