# Generated by Django 5.1.1 on 2025-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_customeraddress_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="state",
            field=models.CharField(
                choices=[
                    ("Stockholm", "Stockholm"),
                    ("Västernorrland", "Västernorrland"),
                    ("Västmanland", "Västmanland"),
                    ("Västra Götaland", "Västra Götaland"),
                    ("Östergötland", "Östergötland"),
                    ("Dalarna", "Dalarna"),
                    ("Gävleborg", "Gävleborg"),
                    ("Gotland", "Gotland"),
                    ("Halland", "Halland"),
                    ("Jämtland", "Jämtland"),
                    ("Jönköping", "Jönköpings"),
                    ("Kalmar", "Kalmar"),
                    ("Kronoberg", "Kronoberg"),
                    ("Norrbotten", "Norrbotten"),
                    ("Örebro", "Örebro"),
                    ("Skåne", "Skåne"),
                    ("Södermanland", "Södermanland"),
                    ("Uppsala", "Uppsala"),
                    ("Värmland", "Värmland"),
                    ("Västerbotten", "Västerbotten"),
                    ("Blekinge", "Blekinge"),
                    ("Nordmaling", "Nordmaling"),
                ],
                max_length=80,
                verbose_name="State",
            ),
        ),
    ]
