# Generated by Django 5.1.1 on 2025-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "session_id",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("is_gift_wrap", models.BooleanField(default=False)),
                (
                    "gift_wrap_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order_packaging_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "delivery_fees",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "taxes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartConfigrations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "gift_wrap_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price for gift wrapping",
                        max_digits=10,
                    ),
                ),
                ("out_of_stock", models.IntegerField(default=5)),
                (
                    "order_packaging_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Charge for packaging the order",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Fee charged by the platform",
                        max_digits=10,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Calculated tax amount",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
