# Generated by Django 5.1.1 on 2025-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="taxes",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
        migrations.AddField(
            model_name="cart",
            name="total_with_vat",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="vat_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
