# Generated by Django 5.1.1 on 2025-02-19 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cart_subtotal_remove_cart_taxes_and_more"),
        ("coupon", "0002_remove_coupon_combinations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("session_id",), name="unique_session_cart"
            ),
        ),
    ]
