# Generated by Django 5.1.1 on 2025-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WelcomePopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="WelcomePopup"),
                ),
                (
                    "navigation_path",
                    models.CharField(
                        blank=True,
                        default="http://192.168.1.20:3000/home",
                        max_length=100,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(default="Shop With Us", max_length=50),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
