# Generated by Django 5.1.1 on 2025-04-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("welcome_popup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="welcomepopup",
            old_name="desc",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="welcomepopup",
            old_name="img",
            new_name="image",
        ),
    ]
