# Generated by Django 5.1.1 on 2025-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("welcome_popup", "0002_rename_desc_welcomepopup_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="welcomepopup",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="welcomepopup",
            name="navigation_path",
            field=models.CharField(
                default="http://192.168.1.20:3000/home", max_length=100
            ),
        ),
    ]
