# Generated by Django 5.1.1 on 2025-01-29 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifyEmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("email_valid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("accountant", "accountant"),
                            ("stock_manager", "stock_manager"),
                            ("worker", "worker"),
                            ("admin", "admin"),
                            ("bakery", "bakery"),
                            ("customer", "customer"),
                        ],
                        default="worker",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                            ("probation", "Probation"),
                            ("resigned", "Resigned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("employee_id", models.CharField(max_length=200, unique=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("Morning", "Day Shift (9 AM - 5 PM)"),
                            ("Night", "Night Shift (11 PM - 7 AM)"),
                            ("Swing", "Swing Shift (3 PM - 11 PM)"),
                        ],
                        default="Morning",
                        max_length=10,
                    ),
                ),
                ("hiring_date", models.DateField()),
                ("terminate_date", models.DateField(null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Stockholm", "Stockholm"),
                            ("Västernorrland", "Västernorrland"),
                            ("Västmanland", "Västmanland"),
                            ("Västra Götaland", "Västra Götaland"),
                            ("Östergötland", "Östergötland"),
                            ("Dalarna", "Dalarna"),
                            ("Gävleborg", "Gävleborg"),
                            ("Gotland", "Gotland"),
                            ("Halland", "Halland"),
                            ("Jämtland", "Jämtland"),
                            ("Jönköping", "Jönköping"),
                            ("Kalmar", "Kalmar"),
                            ("Kristianstad", "Kristianstad"),
                            ("Kopparberg", "Kopparberg"),
                            ("Skåne", "Skåne"),
                            ("Södermanland", "Södermanland"),
                            ("Uppsala", "Uppsala"),
                            ("Värmland", "Värmland"),
                            ("Västerbotten", "Västerbotten"),
                            ("Blekinge", "Blekinge"),
                            ("Nordmaling", "Nordmaling"),
                            ("Örebro", "Örebro"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("SE", "SWEDEN")],
                        default="SE",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
                (
                    "contact_no",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10,15}$",
                                message="Enter a valid contact number with 10-15 digits.",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PasswordResetOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
