# Generated by Django 5.1.1 on 2025-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_stripecustomer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
