# Generated by Django 5.1.1 on 2025-04-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_registrationtoken_employeedetail_job_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("individual", "individual"), ("company", "company")],
                default="individual",
                max_length=12,
            ),
        ),
    ]
