# Generated by Django 5.1.1 on 2025-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="org_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="org_number",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vat_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
