# Generated by Django 5.1.1 on 2025-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_customuser_company_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="company_domain",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="org_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="org_number",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("individual", "individual"), ("company", "company")],
                default="individual",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vat_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
