# Generated by Django 5.1.1 on 2025-04-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_customuser_company_domain_customuser_org_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="company_domain",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="org_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="org_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="vat_id",
        ),
    ]
