# Generated by Django 5.1.1 on 2025-02-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day", models.CharField(blank=True, max_length=9, null=True)),
                ("holiday", models.CharField(max_length=100)),
                ("restricted", models.BooleanField(default=False)),
            ],
        ),
    ]
