# Generated by Django 5.1.7 on 2025-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("holiday", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="holiday",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
