# Generated by Django 5.1.1 on 2025-01-30 05:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "coupon_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Coupon Name",
                    ),
                ),
                (
                    "coupon_description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Coupon Description",
                    ),
                ),
                ("code", models.CharField(unique=True)),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("buy_x_get_y", "Buy X Get Y"),
                            ("amount_off_product", "Amount Off Product"),
                            ("amount_off_order", "Amount Off Order"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        default="buy_x_get_y",
                        max_length=100,
                        verbose_name="Coupon Type",
                    ),
                ),
                (
                    "minimum_purchase_requirement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_requirement", "No Minimum Purchase Requirement"),
                            ("minimum_purchase", "Minimum Purchase Amount"),
                            ("minimum_items", "Minimum Quantity Of Items"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Minimum Purchase Requirement",
                    ),
                ),
                (
                    "minimum_purchase_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "customer_eligibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_customer", "All Customer"),
                            ("specific_customer", "Specific Customer"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Customer Eligibility",
                    ),
                ),
                (
                    "customer_specification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("havent_purchased", "Haven't Purchased"),
                            ("recent_purchased", "Recent Purchased"),
                            ("purchased_once", "Purchased Once"),
                            ("purchased_more_than_once", "Purchased More Than Once"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Customer Specification",
                    ),
                ),
                (
                    "maximum_discount_usage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("per_customer", "Use Per Customer"),
                            (
                                "limit_discount_usage_time",
                                "Limit Number of Times Discount Usage",
                            ),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="Maximum Discount Usage",
                    ),
                ),
                ("maximum_usage_value", models.IntegerField(default=0)),
                (
                    "combinations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("product_discounts", "Product Discounts"),
                                ("basket_discounts", "Basket Discounts"),
                                ("order_discounts", "Order Discounts"),
                                ("shipping_discounts", "Shipping Discounts"),
                            ],
                            max_length=100,
                        ),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "shipping_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("all_states", "All States"),
                            ("specific_states", "Specific States"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Shipping Scope",
                    ),
                ),
                (
                    "shipping_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Shipping Rate",
                    ),
                ),
                ("exclude_shipping_rate", models.BooleanField(default=False)),
                (
                    "discount_types",
                    models.CharField(
                        blank=True,
                        choices=[("percentage", "percentage"), ("amount", "amount")],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Discount Types",
                    ),
                ),
                ("discount_value", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField()),
                (
                    "customer_buy_types",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minimum_items_quantity", "Minimum Items Quantity"),
                            ("minimum_purchase_amount", "Minimum Purchase Amount"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Customer Buy Types",
                    ),
                ),
                (
                    "buy_products_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "buy_basket_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "customer_gets_types",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("amount_off_each", "Amount Off Each"),
                            ("percentage", "Percentage"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Customer Get Types",
                    ),
                ),
                ("customer_gets_quantity", models.IntegerField(default=0)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Current number of times this coupon has been used",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("specific_products", "Specific Products"),
                            ("all_products", "All Products"),
                            ("specific_baskets", "Specific Baskets"),
                            ("all_baskets", "All Baskets"),
                        ],
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="Coupon Applies Types",
                    ),
                ),
                ("customer_gets_discount_value", models.IntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "buy_baskets",
                    models.ManyToManyField(
                        blank=True, related_name="coupons_baskets", to="product.basket"
                    ),
                ),
                (
                    "buy_products",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="product.productvariant"
                    ),
                ),
                (
                    "customer_get_basket",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customer_get_basketcoupons",
                        to="product.basket",
                    ),
                ),
                (
                    "customer_get_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="customer_get_coupons",
                        to="product.productvariant",
                    ),
                ),
                (
                    "specific_baskets",
                    models.ManyToManyField(
                        blank=True, related_name="specific_baskets", to="product.basket"
                    ),
                ),
                (
                    "specific_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specific_products",
                        to="product.productvariant",
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select specific states if shipping scope is 'Specific States'",
                        related_name="coupons",
                        to="coupon.state",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("redeemed", models.BooleanField(default=False)),
                ("redemption_date", models.DateTimeField(blank=True, null=True)),
                ("maximum_usage", models.IntegerField(default=0)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="coupon.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
