# Generated by Django 5.1.1 on 2025-01-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="combinations",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="coupon_description",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="coupon_name",
        ),
        migrations.RemoveField(
            model_name="state",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="state",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="usercoupon",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="usercoupon",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="coupon",
            name="combination",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_discounts", "Product Discounts"),
                    ("basket_discounts", "Basket Discounts"),
                    ("order_discounts", "Order Discounts"),
                    ("shipping_discounts", "Shipping Discounts"),
                ],
                default=None,
                max_length=100,
                null=True,
                verbose_name="Combination",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="customer_get_quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="get_applies_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("specific_products", "Specific Products"),
                    ("all_products", "All Products"),
                    ("specific_baskets", "Specific Baskets"),
                    ("all_baskets", "All Baskets"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Coupon Get Apply Types",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_item_value",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="buy_products_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
