# Generated by Django 5.1.1 on 2025-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("reorder_level", models.IntegerField(default=100)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("out_of_stock", models.IntegerField(default=5)),
                (
                    "shipping_charges",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "packing_fee",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdminInvoiceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                ("company_address", models.TextField(blank=True, null=True)),
                (
                    "company_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZipCodeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("zip_code", models.CharField(max_length=6, unique=True)),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Stockholm", "Stockholm"),
                            ("Västernorrland", "Västernorrland"),
                            ("Västmanland", "Västmanland"),
                            ("Västra Götaland", "Västra Götaland"),
                            ("Östergötland", "Östergötland"),
                            ("Dalarna", "Dalarna"),
                            ("Gävleborg", "Gävleborg"),
                            ("Gotland", "Gotland"),
                            ("Halland", "Halland"),
                            ("Jämtland", "Jämtland"),
                            ("Jönköping", "Jönköping"),
                            ("Kalmar", "Kalmar"),
                            ("Kristianstad", "Kristianstad"),
                            ("Kopparberg", "Kopparberg"),
                            ("Skåne", "Skåne"),
                            ("Södermanland", "Södermanland"),
                            ("Uppsala", "Uppsala"),
                            ("Värmland", "Värmland"),
                            ("Västerbotten", "Västerbotten"),
                            ("Blekinge", "Blekinge"),
                            ("Nordmaling", "Nordmaling"),
                            ("Örebro", "Örebro"),
                        ],
                        default="Blekinge",
                        max_length=100,
                    ),
                ),
                ("min_order_quantity", models.PositiveIntegerField()),
                (
                    "delivery_availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=13,
                    ),
                ),
                ("delivery_threshold", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("address", models.TextField(blank=True)),
                (
                    "country",
                    models.CharField(
                        choices=[("SE", "SWEDEN")],
                        default="SE",
                        max_length=100,
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
