# Generated by Django 5.1.7 on 2025-03-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_zipcodeconfig_delivery_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="account_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="iban_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="organization_no",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="admininvoiceconfiguration",
            name="vat_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
