# Generated by Django 5.1.7 on 2025-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_admininvoiceconfiguration_account_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminconfiguration",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
