# Generated by Django 5.1.7 on 2025-03-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_adminconfiguration_company_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminconfiguration",
            name="company_logo",
        ),
    ]
