# Generated by Django 5.1.1 on 2025-04-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_remove_adminconfiguration_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zipcodeconfig",
            name="zip_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
