# Generated by Django 5.1.1 on 2025-04-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_zipcodeconfig_zip_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerQuery",
        ),
    ]
