# Generated by Django 5.1.1 on 2025-01-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="updated_at",
        ),
    ]
