# Generated by Django 5.1.1 on 2025-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="offer",
        ),
        migrations.AddField(
            model_name="basket",
            name="end_sale",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="basket",
            name="is_active_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="basket",
            name="start_sale",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="BasketOffer",
        ),
    ]
