# Generated by Django 5.1.1 on 2025-02-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_remove_basket_offer_basket_end_sale_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="serial_number",
        ),
        migrations.AddField(
            model_name="holiday",
            name="restrict_holiday",
            field=models.BooleanField(default=False),
        ),
    ]
