# Generated by Django 5.1.1 on 2025-02-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_holiday_serial_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="holiday",
            old_name="restrict_holiday",
            new_name="restricted",
        ),
    ]
