# Generated by Django 5.1.1 on 2025-02-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_rename_restrict_holiday_holiday_restricted"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Holiday",
        ),
    ]
