# Generated by Django 5.1.7 on 2025-03-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_delete_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="offer_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
