# Generated by Django 5.1.7 on 2025-03-19 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_basket_offer_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productmaterial",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, upload_to="material_barcodes/"
            ),
        ),
        migrations.AddField(
            model_name="productmaterial",
            name="unique_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="productmaterial",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_raw_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
