# Generated by Django 5.1.7 on 2025-03-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0007_productmaterial_barcode_productmaterial_unique_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("publish", "Publish")],
                default="publish",
                max_length=10,
            ),
        ),
    ]
