# Generated by Django 5.1.7 on 2025-03-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_basket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
