# Generated by Django 5.1.1 on 2025-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_inventory_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="is_customizable",
            field=models.BooleanField(default=False),
        ),
    ]
