# Generated by Django 5.1.1 on 2025-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripeinvoice",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="stripeinvoice",
            name="amount_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stripeinvoice",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="stripeinvoice",
            name="customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="stripeinvoice",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
